services:
    nginx:
        container_name: reon_nginx
        image: nginx:latest
        restart: no
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - backend
        networks:
            - dev

    backend:
        container_name: reon_backend
        build:
            context: .
            dockerfile: Dockerfile
        restart: no
        env_file:
            - .env
        ports:
            - '5000:5000'
        depends_on:
            - postgres
        networks:
            - dev

    postgres:
        container_name: postgres_reon
        image: postgres:17.2
        restart: no
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - '5432:5432'
        volumes:
            - postgres_data_reon:/var/lib/postgresql/data
        networks:
            - dev

volumes:
    postgres_data_reon:
networks:
    dev:
        driver: bridge
